### ISSUE TITLE
Y offset for Party Numbers / Cooldown Bars is not sufficient for higher resolutions

### ISSUE THREAD

**Issue by Yentis** [priprii/GenshinOverlay#1]
On 2560x1440 a Y offset of 100 is not enough 
![image](https://user-images.githubusercontent.com/17981128/96191020-898ee180-0f43-11eb-8858-0ca802eb79bd.png)
![image](https://user-images.githubusercontent.com/17981128/96191115-bc38da00-0f43-11eb-938e-aa0e6552a532.png)

**Comment by priprii** [comment]
Ah this is something I forgot to take into account because I didn't have a bigger resolution to work with.
I'll be changing how party numbers are setup regardless.

**Comment by tinbtb** [comment]
As expected, same issue here, too bad that the offset numbers couldn't be set to higher values even through the config. Hoping for a quick fix :)

BTW, I think that adding info about the options needed to run the game in borderless mode (i.e. -popupwindow) to README.md would help a lot of future users.

**Comment by priprii** [comment]
I made a new commit with most of the changes. Haven't added the min/max values to config yet but I doubled the bar offset and detecting party numbers has been overhauled to be individually assignable to support higher resolutions & controllers and also support fewer than 4 party members.

It's not completely ready yet, there's a bit of a flicker issue when switching party members I need to sort out but I'm off now.

**Comment by Skullpluggery** [comment]
> I made a new commit with most of the changes. Haven't added the min/max values to config yet but I doubled the bar offset and detecting party numbers has been overhauled to be individually assignable to support higher resolutions & controllers and also support fewer than 4 party members.
> 
> It's not completely ready yet, there's a bit of a flicker issue when switching party members I need to sort out but I'm off now.

Been using this! I would be glad to help but I just found that you're using C#. I know the language but I uninstalled my VS Studio already (cuz it's hella big) HAHAHA! Would be better if you picked a different language such as JS (Electron)

**Comment by priprii** [comment]
Release version of v1.1 is now available which addresses this issue.
