### ISSUE TITLE
Process Error

### ISSUE THREAD

**Issue by Flocculus** [priprii/GenshinOverlay#10]
It just says Process Error...? Could you please let me know how to solve it? Thx

**Comment by priprii** [comment]
It shouldn't just say "Process Error"?
It should say "Genshin Impact must be running first"... so you can fix it by making sure the game is running and is not minimized and is not fullscreen.

**Comment by Flocculus** [comment]
Solved.
The reason is that the process name of mine is YuanShen but not Genshin Impact. Need to fixed it in the ini file.
