### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Franzelinux** [priprii/GenshinOverlay#12]
In the readme you stated to start GenshinOverlay as Admin maybe you should add wich GenshinOverlay since you have GenshinOverlay.csproj GenshinOverlay.ico and GenshinOverlay.sln and that you need Visual Studio to open sln files
(i say that because i was to stupid for it and had to google all the endings to find what the problem could be)

**Comment by priprii** [comment]
You're referring to the source files which you should only download if you're a developer.
Go to Releases if you want the public release binary
