### ISSUE TITLE
Mona Skill Cooldown location not same as everyone

### ISSUE THREAD

**Issue by sasahara00** [priprii/GenshinOverlay#2]
Mona / Ayaka has different skill set than other characters in game.

they have dash as one of their skill so E location is not same as anyone in the game.

would suggest have two location for program to detect cooldown timer? 

thank you

**Comment by priprii** [comment]
Could you provide a video of how Mona's skill works.

**Comment by chocosobo** [comment]
![image](https://user-images.githubusercontent.com/6840644/96531871-93a73c00-12c5-11eb-8a85-8e469ffde832.png)

mona's passive replace dash and push E to left side
maybe set skill location per character needed
for future update characters like ayaka, rumored on 1.1 patch

**Comment by priprii** [comment]
For now I'll just add a secondary rectangle to setup for characters like this.

**Comment by priprii** [comment]
v1.5 may fix this issue, I can't test it myself so please confirm if it does fix it.

**Comment by chocosobo** [comment]
works very fine with mona
