### ISSUE TITLE
Fischl cooldown is not detected

### ISSUE THREAD

**Issue by tinbtb** [priprii/GenshinOverlay#5]
Fischl skill consists of at least two cooldowns (up to ~7). The initial cooldown (~1.5s) is detected correctly, but the long final cooldown (~15s) is not detected.

**Comment by tinbtb** [comment]
Correction: the final cooldown can be detected if "E" button is pressed when it's started.

**Comment by priprii** [comment]
You need to set cooldown override for characters like Fischl, it's explained in the readme under "Configure Overlay - Cooldown Override".

For Fischl, an override of 23sec - 24sec is fine.

**Comment by tinbtb** [comment]
Thank you for the explanation.
