### ISSUE TITLE
Cooldown isnt detected if its greater than 60 seconds.

### ISSUE THREAD

**Issue by mactassio** [priprii/GenshinOverlay#9]
Title basically.
This issue happens on domains or abyss rooms that increase your cooldowns and if any of them is greater than 60 the cooldown bar cant tell if its on cooldown or not.
To recreate the bug, try barbara on the water domain.

**Comment by priprii** [comment]
There's an option called "Max" which defines the max possible cooldown that can be detected, by default this is 60sec, you can just change it to something higher.
